name: Integration Tests
on:
    push:
        branches:
            - main
        paths-ignore:
            - "**.MD"
            - "**.md"

permissions:
    contents: read
    id-token: write

jobs:
    run-e2e-tests:
        runs-on:
            group: databricks-protected-runner-group
            labels: linux-ubuntu-latest
        environment: azure-prod
        env:
            DATABRICKS_SERVER_HOSTNAME: ${{ secrets.DATABRICKS_HOST }}
            DATABRICKS_HTTP_PATH: ${{ secrets.TEST_PECO_WAREHOUSE_HTTP_PATH }}
            DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
            DATABRICKS_CATALOG: ${{ secrets.SQLALCHEMY_CATALOG }}
            DATABRICKS_SCHEMA: ${{ secrets.SQLALCHEMY_SCHEMA }}
            DATABRICKS_USER: ${{ secrets.TEST_PECO_SP_ID }}
        steps:
            - name: Check out repository
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
            - name: Setup Poetry
              uses: ./.github/actions/setup-poetry
              with:
                  python-version: "3.10"
                  install-args: "--all-extras"
            - name: Run SQL Alchemy tests
              run: poetry run python -m pytest tests/test_local
